language: perl
perl:
- "5.26"
- "5.24"
- "5.22"
- "5.20"
cache:
  directories:
    -
install:
  - cpanm --installdeps ./code/
  - export PERL5LIB=./code/modules
script:
  - perl ./code/scripts/assign_genome_properties.pl -all -gpdir ./flatfiles -gpff genomeProperties.txt -matches testing/testfiles/ecoli_k12_annotation.tsv -outdir ./ -outfiles summary -name ecoli_k12
  - test -s ./SUMMARY_FILE_ecoli_k12
  - ls -l /home/travis/perl5/perlbrew/perls/5.26.2/lib/5.26.2/
notifications:
    email: false